from optax_optim._shampoo import scale_by_shampoo
from optax_optim._muon import scale_by_muon
from optax_optim._adam import scale_by_adam
from optax_optim._sgd import scale_by_momentum
from optax_optim._static_preconditioner import static_scale_by_adam, static_scale_by_identity, static_scale_by_shampoo, static_scale_by_muon
from optax_optim._kron import scale_by_kron
from optax_optim._soap import scale_by_soap
from optax_optim._soap_bucketed import scale_by_soap_bucketed